### ISSUE TITLE
Progress Checklist

### ISSUE THREAD

**Issue by jackmott** [jackmott/LinqFaster#2]
- [x] Regular Linq Extension Method Coverage
- [x] Regular Linq Extension Method Tests

- [x] Parallel Linq Extension Method Coverage
- [x] Parallel Linq Extension Method Tests

- [x] SIMD Linq Extension Method Coverage
- [x] SIMD Linq Extension Method Tests

- [x] Parallel SIMD Linq Extension Method Coverage
- [x] Parallel SIMD Linq Extension Method Tests

**Comment by Smurf-IV** [comment]
Should include all `base` types for each if these, just to be sure that the answers are correct.
